### PR TITLE
Completed Proposal

### LINKED ISSUE #1: Complete Project Proposal
We can use this area to brainstorm. Also, [here's a copy of the proposal description](https://sites.google.com/site/datavisualizationspring2019/term-project/1-proposal):

> (This part is worth 7 points of the 46 term project points)
>
> Project proposals should be simple and to the point. Proposals should not exceed two pages. The proposal should include, but is not limited to, the following:
> 
> - Title that clearly indicates the topic of the proposal
> - Brief abstract (3-4 sentences) giving a summary of your proposal
> - Names and contact information for all students working jointly on the project
> - Introduction and motivation/rationale for the project (Why are you doing this project? Why is it important?)
> - Research questions you will be addressing
> - List of design goals
> - Hardware and software you will use to complete your implementation (displays, input devices, toolkits, languages, etc.)
> - Tasks and metrics you might use to evaluate the goals
> 
> Potential impact of the project (How might the results of your project extend the state-of-the-art in VIS, or enhance or impact a particular application area, etc.?)
> 
> Please use the paper format here and use it for the rest of the project submissions.
> 
> Examples of good project proposals: please check the piazza page. 
> 
> Please schedule a meeting with TA and Dr. Chen to get approval for your project scope.

### PR DESCRIPTION
**Pull request by jrg94**
Fixes #1.

All done! Feel free to take a look at the raw LaTeX. I've also attached a working copy of the PDF for your viewing pleasure. Let me know if there are any changes you'd like to see.

[proposal.pdf](https://github.com/jrg94/data-viz-term-project/files/2898645/proposal.pdf)

### CODE REVIEW

**Comment by wustep** [comment]
this is awesome! thanks for tackling this. I'll get on presentation asap. 

1. I would revise the research questions to be more precise and really hit the meat of things
    - the wording of "prioritize practice areas in our visualization" is kinda awkward and not precise. Maybe a better question is: "What are practice areas and quantifiable data (pitch, tempo, etc.) that we can gleam from MIDI recordings?" 
    - I would drop question 3 and combine it, since it just addresses one graph
    - "What are our options in analyzing MIDI files to visualize MIDI events in a useful manner for musicians?"
    - "How useful is comparing MIDI recordings via velocity, sustain, and note frequency over time graphs?"
    - "Can we algorithmically generate useful automated feedback from analysis of these MIDI recordings and graphs?" 

2. 19 seems like an odd number, and we don't reaelly need to specify a max in this proposal anyway

3. we prob won't need garageband, but I would write "GarageBand" withtout the space

4. in the tasks & metrics, we need to talk about Metrics that we'd be evaluating the research on. I think we can just say we'll have musicians of different levels assess the tool by comparing their "guesses" of how well they played / areas of improvement to the graph. More work on this later.

will respond later with some additional thoughts

**Comment by wustep** [comment]
also we should get rid of the template text "Manuscript received xx xxx. 201x; accepted xx xxx. 201x. Date of Publication
xx xxx. 201x; date of current version xx xxx. 201x. For information on
obtaining reprints of this article, please send e-mail to: reprints@ieee.org.
Digital Object Identifier: xx.xxxx/TVCG.201x.xxxxxxx"

**Comment by jrg94** [comment]
That last part is required according to the template. That's the only reason it's there.

> This template is for papers of VGTC-sponsored conferences such as IEEE VIS, IEEE VR, and ISMAR which are published as special issues of TVCG. The template does not contain the respective dates of the conference/journal issue, these will be entered by IEEE as part of the publication production process. Therefore, \textbf{please leave the copyright statement at the bottom-left of this first page untouched}.

**Comment by jrg94** [comment]
For reference, 19 is the maximum number of colors we can perceive (according to professor Chen). That's why that number is there.

**Comment by jrg94** [comment]
The GarageBand typo is fixed.

**Comment by jrg94** [comment]
Added some information about metrics

**Comment by jrg94** [comment]
Updated the 19 to "about 20" and clarified color perception limitations.

**Comment by jrg94** [comment]
Replaced research questions. Will generate a new PDF for feedback.

**Comment by jrg94** [comment]
Here's the latest proposal: [proposal.pdf](https://github.com/jrg94/data-viz-term-project/files/2911871/proposal.pdf).

If there are no qualms, I'll rework the homepage, so there's a link to the PDF.

**Pull request merged**
