### PR TITLE
Cleanup - big refactor into 7 files

### PR DESCRIPTION
**Pull request by wustep**
Refactoring dashboard.js into 7 files... RIP git history. I'm not sure this method is exactly ideal (using `this.dashboard.panes.graphView.function` is pretty lengthy) and some things might go better in other places, but it's a start! Let me know what you think

```
  <script src="js/Utils.js"></script>
  <script src="js/MidiFilePane.js"></script>
  <script src="js/NotesPlayedPane.js"></script>
  <script src="js/NotesVelocityPane.js"></script>
  <script src="js/NotesFrequencyPane.js"></script>
  <script src="js/GraphViewPane.js"></script>
  <script src="js/Dashboard.js"></script>

```

### CODE REVIEW

**Comment by wustep** [comment]
Possible improvement, using `_` for "private" functions in each class

**Comment by jrg94** [comment]
So, is that how JavaScript handles private? I know Python is like that.

**Review by jrg94 — APPROVED** [review]
Love these changes. I really like that you created a dashboard object, so we're no longer tracking loads of global variables.

**Comment by wustep** [comment]
Not exactly, vanilla JS doesn't have private class functions exactly but adding a _ is a convention to say it shouldn't be used outside of this class

**Comment by jrg94** [comment]
I believe that's how Python handles "private" functions. There's no special keyword, but IDEs respect the underscore notation. I'm cool with it!

**Comment by jrg94** [comment]
Gonna merge this is (assuming it works).

**Pull request merged**
