### PR TITLE
Restored Old Prototype Folder and Created New Production Folder

### LINKED ISSUE #39: Duplicate Prototype Code into Final Folder
Apparently, we have to submit the prototype separate from the final version. Before we make anymore changes, we should create a copy of our work and put it into a new folder.

Prototype: https://sites.google.com/site/datavisualizationspring2019/term-project/project-prototype
Piazza: https://piazza.com/class/jqq33mm5jmr657?cid=48

### PR DESCRIPTION
**Pull request by jrg94**
To do this, I branched from the last commit before the presentation. I then duplicated the prototype folder and merged current changes back. Current prototype folder was renamed src and and duplicate folder was given the prototype name.

Not sure if this destroys history, but it gets the job done.

Fixes #39.

### CODE REVIEW

**Comment by wustep** [comment]
Do you think we can get rid of the extra midiviz folder layer and just have src and prototype in root?

**Comment by jrg94** [comment]
Yup! I can do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
I'd also advocate for the renaming of the src folder, so the production link is prettier haha

**Comment by jrg94** [comment]
Alright, I made some changes to project structure. Let me know if this looks good to you.

**Comment by jrg94** [comment]
I'm going to go ahead and pull this in. Looking to work on the playback marker functionality next.

**Pull request merged**
